spring:
  application:
    name: who-am-ai

  data:
    mongodb:
      uri: ${MONGO_URI}

server:
  port: 8080

file:
  upload-url: "cloudinary://${CLOUDINARY_KEY}:${CLOUDINARY_SECRET}@${CLOUDINARY_NAME}"

gemini:
  api:
    key: ${GEMINI_API_KEY}
  model:
    name: "gemini-2.5-flash-lite-preview-06-17"